name: Homa Daily Jobs

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  find-and-send-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Homa Jobs Bot
        env:
          GEMINI_API_KEY:   ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN:   ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
